version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\Andrey\mycomiclibrary\BData\mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=MyComic
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1man